FROM golang:1.12 as build

COPY . /frp
WORKDIR /frp

RUN make frps

# ------

FROM alpine:3.11

RUN apk --no-cache add bash libc6-compat tzdata

COPY --from=build /frp/bin/frps /frps

WORKDIR /

EXPOSE 80 443 6000 7000 7500

CMD ["/frps"]
